// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AddGitRepoRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Git repository URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocsRepoUrl { get; set; }
#nullable restore
#else
        public string DocsRepoUrl { get; set; }
#endif
        /// <summary>Generate documentation from the repository source code. Applies to private repository submissions.</summary>
        public bool? GenerateDocs { get; set; }
        /// <summary>Personal access token for private repositories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitToken { get; set; }
#nullable restore
#else
        public string GitToken { get; set; }
#endif
        /// <summary>Whether the repository is private</summary>
        public bool? Private { get; set; }
        /// <summary>Skip filtering out version-specific documentation pages</summary>
        public bool? SkipVersionFiltering { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.AddGitRepoRequest"/> and sets the default values.
        /// </summary>
        public AddGitRepoRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.AddGitRepoRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.AddGitRepoRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.AddGitRepoRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "docsRepoUrl", n => { DocsRepoUrl = n.GetStringValue(); } },
                { "generateDocs", n => { GenerateDocs = n.GetBoolValue(); } },
                { "gitToken", n => { GitToken = n.GetStringValue(); } },
                { "private", n => { Private = n.GetBoolValue(); } },
                { "skipVersionFiltering", n => { SkipVersionFiltering = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("docsRepoUrl", DocsRepoUrl);
            writer.WriteBoolValue("generateDocs", GenerateDocs);
            writer.WriteStringValue("gitToken", GitToken);
            writer.WriteBoolValue("private", Private);
            writer.WriteBoolValue("skipVersionFiltering", SkipVersionFiltering);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
