// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>Set to &apos;true&apos; to force reprocessing</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddOpenApiUploadFormDataRequestForce
    {
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
    }
}
