// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// A code snippet from library documentation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CodeSnippet : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description of what the code does</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeDescription { get; set; }
#nullable restore
#else
        public string CodeDescription { get; set; }
#endif
        /// <summary>URL to source location</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeId { get; set; }
#nullable restore
#else
        public string CodeId { get; set; }
#endif
        /// <summary>Primary programming language</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeLanguage { get; set; }
#nullable restore
#else
        public string CodeLanguage { get; set; }
#endif
        /// <summary>Code examples in different languages</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.CodeExample>? CodeList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.CodeExample> CodeList { get; set; }
#endif
        /// <summary>Title of the code snippet</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CodeTitle { get; set; }
#nullable restore
#else
        public string CodeTitle { get; set; }
#endif
        /// <summary>Token count for the snippet</summary>
        public int? CodeTokens { get; set; }
        /// <summary>Whether this snippet was recovered from the dynamic source-code index instead of the primary docs index</summary>
        public bool? IsDynamic { get; set; }
        /// <summary>Title of the documentation page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageTitle { get; set; }
#nullable restore
#else
        public string PageTitle { get; set; }
#endif
        /// <summary>Repo-relative source file path for dynamic snippets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceFile { get; set; }
#nullable restore
#else
        public string SourceFile { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet"/> and sets the default values.
        /// </summary>
        public CodeSnippet()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codeDescription", n => { CodeDescription = n.GetStringValue(); } },
                { "codeId", n => { CodeId = n.GetStringValue(); } },
                { "codeLanguage", n => { CodeLanguage = n.GetStringValue(); } },
                { "codeList", n => { CodeList = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CodeExample>(global::Soenneker.Context7.OpenApiClient.Models.CodeExample.CreateFromDiscriminatorValue)?.AsList(); } },
                { "codeTitle", n => { CodeTitle = n.GetStringValue(); } },
                { "codeTokens", n => { CodeTokens = n.GetIntValue(); } },
                { "isDynamic", n => { IsDynamic = n.GetBoolValue(); } },
                { "pageTitle", n => { PageTitle = n.GetStringValue(); } },
                { "sourceFile", n => { SourceFile = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("codeDescription", CodeDescription);
            writer.WriteStringValue("codeId", CodeId);
            writer.WriteStringValue("codeLanguage", CodeLanguage);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CodeExample>("codeList", CodeList);
            writer.WriteStringValue("codeTitle", CodeTitle);
            writer.WriteIntValue("codeTokens", CodeTokens);
            writer.WriteBoolValue("isDynamic", IsDynamic);
            writer.WriteStringValue("pageTitle", PageTitle);
            writer.WriteStringValue("sourceFile", SourceFile);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
