// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Documentation context response
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContextResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Relevant code snippets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet>? CodeSnippets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet> CodeSnippets { get; set; }
#endif
        /// <summary>Relevant documentation snippets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.InfoSnippet>? InfoSnippets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.InfoSnippet> InfoSnippets { get; set; }
#endif
        /// <summary>Optional library-specific rules and guidelines</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.ContextResponseRules? Rules { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.ContextResponseRules Rules { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.ContextResponse"/> and sets the default values.
        /// </summary>
        public ContextResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.ContextResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.ContextResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.ContextResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "codeSnippets", n => { CodeSnippets = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet>(global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet.CreateFromDiscriminatorValue)?.AsList(); } },
                { "infoSnippets", n => { InfoSnippets = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.InfoSnippet>(global::Soenneker.Context7.OpenApiClient.Models.InfoSnippet.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rules", n => { Rules = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ContextResponseRules>(global::Soenneker.Context7.OpenApiClient.Models.ContextResponseRules.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CodeSnippet>("codeSnippets", CodeSnippets);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.InfoSnippet>("infoSnippets", InfoSnippets);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ContextResponseRules>("rules", Rules);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
