// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>Processing state of the library</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LibraryState
    {
        [EnumMember(Value = "finalized")]
        #pragma warning disable CS1591
        Finalized,
        #pragma warning restore CS1591
        [EnumMember(Value = "initial")]
        #pragma warning disable CS1591
        Initial,
        #pragma warning restore CS1591
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
    }
}
