// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Library usage metrics response
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibraryMetricsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Lifetime country distribution (ISO-2 codes), ordered by count descending</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.CountryCount>? Countries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.CountryCount> Countries { get; set; }
#endif
        /// <summary>Per-day request counts (deltas, not cumulative), ordered from oldest to newest. Days with zero activity are omitted. Up to `days` points — fewer if the library has less history or had idle days in the window.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.DailyStatsPoint>? Daily { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.DailyStatsPoint> Daily { get; set; }
#endif
        /// <summary>MCP client usage breakdown by day</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.McpClientMetrics? McpClients { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.McpClientMetrics McpClients { get; set; }
#endif
        /// <summary>Lifetime topic distribution, ordered by count descending</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.TopicCount>? Topics { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.TopicCount> Topics { get; set; }
#endif
        /// <summary>Cumulative request counts for a library, broken down by request surface</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.ProjectStats? Total { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.ProjectStats Total { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.LibraryMetricsResponse"/> and sets the default values.
        /// </summary>
        public LibraryMetricsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.LibraryMetricsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.LibraryMetricsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.LibraryMetricsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "countries", n => { Countries = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CountryCount>(global::Soenneker.Context7.OpenApiClient.Models.CountryCount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "daily", n => { Daily = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.DailyStatsPoint>(global::Soenneker.Context7.OpenApiClient.Models.DailyStatsPoint.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mcpClients", n => { McpClients = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.McpClientMetrics>(global::Soenneker.Context7.OpenApiClient.Models.McpClientMetrics.CreateFromDiscriminatorValue); } },
                { "topics", n => { Topics = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.TopicCount>(global::Soenneker.Context7.OpenApiClient.Models.TopicCount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total", n => { Total = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ProjectStats>(global::Soenneker.Context7.OpenApiClient.Models.ProjectStats.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.CountryCount>("countries", Countries);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.DailyStatsPoint>("daily", Daily);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.McpClientMetrics>("mcpClients", McpClients);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.TopicCount>("topics", Topics);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ProjectStats>("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
