// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Library metadata
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Library : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Quality indicator score (0-100)</summary>
        public double? BenchmarkScore { get; set; }
        /// <summary>Git branch being tracked</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>Short description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Library ID — the URL path of the library on context7.com. `/owner/repo` for GitHub repositories, or `/&lt;source&gt;/&lt;id&gt;` for other sources (e.g., `/vercel/next.js`, `/websites/uploadcare_com`). See [Library ID format](/api-guide#library-id-format).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>ISO 8601 timestamp of last update</summary>
        public DateTimeOffset? LastUpdateDate { get; set; }
        /// <summary>GitHub stars count</summary>
        public int? Stars { get; set; }
        /// <summary>Processing state of the library</summary>
        public global::Soenneker.Context7.OpenApiClient.Models.LibraryState? State { get; set; }
        /// <summary>Display name of the library</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>Number of code snippets</summary>
        public int? TotalSnippets { get; set; }
        /// <summary>Total tokens in documentation</summary>
        public int? TotalTokens { get; set; }
        /// <summary>Source reputation score (0-10)</summary>
        public int? TrustScore { get; set; }
        /// <summary>Available version tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Versions { get; set; }
#nullable restore
#else
        public List<string> Versions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.Library"/> and sets the default values.
        /// </summary>
        public Library()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.Library"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.Library CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.Library();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "benchmarkScore", n => { BenchmarkScore = n.GetDoubleValue(); } },
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastUpdateDate", n => { LastUpdateDate = n.GetDateTimeOffsetValue(); } },
                { "stars", n => { Stars = n.GetIntValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Context7.OpenApiClient.Models.LibraryState>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "totalSnippets", n => { TotalSnippets = n.GetIntValue(); } },
                { "totalTokens", n => { TotalTokens = n.GetIntValue(); } },
                { "trustScore", n => { TrustScore = n.GetIntValue(); } },
                { "versions", n => { Versions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("benchmarkScore", BenchmarkScore);
            writer.WriteStringValue("branch", Branch);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastUpdateDate", LastUpdateDate);
            writer.WriteIntValue("stars", Stars);
            writer.WriteEnumValue<global::Soenneker.Context7.OpenApiClient.Models.LibraryState>("state", State);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("totalSnippets", TotalSnippets);
            writer.WriteIntValue("totalTokens", TotalTokens);
            writer.WriteIntValue("trustScore", TrustScore);
            writer.WriteCollectionOfPrimitiveValues<string>("versions", Versions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
