// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Per-day MCP client unique users for a library
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class McpDailyClientData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>UTC date in `YYYY-MM-DD` format</summary>
        public Date? Date { get; set; }
        /// <summary>Total unique users across all clients for this library on this date</summary>
        public int? TotalUniqueUsers { get; set; }
        /// <summary>Unique user count per MCP client identifier (e.g., `cursor`, `claude-code`, `codex`)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientDataUniqueUsersByClientProperty? UniqueUsersByClient { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientDataUniqueUsersByClientProperty UniqueUsersByClient { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientData"/> and sets the default values.
        /// </summary>
        public McpDailyClientData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetDateValue(); } },
                { "totalUniqueUsers", n => { TotalUniqueUsers = n.GetIntValue(); } },
                { "uniqueUsersByClient", n => { UniqueUsersByClient = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientDataUniqueUsersByClientProperty>(global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientDataUniqueUsersByClientProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("date", Date);
            writer.WriteIntValue("totalUniqueUsers", TotalUniqueUsers);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.McpDailyClientDataUniqueUsersByClientProperty>("uniqueUsersByClient", UniqueUsersByClient);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
