// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Update quality-mode settings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchPoliciesRequestLibraryFiltersQuality : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Incremental add/remove operation on a list of library identifiers or domains. Use &apos;clear&apos; to remove all entries at once.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.ListOperation? BlockedLibraries { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.ListOperation BlockedLibraries { get; set; }
#endif
        /// <summary>Incremental add/remove operation on a list of library identifiers or domains. Use &apos;clear&apos; to remove all entries at once.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.ListOperation? ExceptedLibraries { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.ListOperation ExceptedLibraries { get; set; }
#endif
        /// <summary>Maximum age in days (null to clear)</summary>
        public int? MaxAgeDays { get; set; }
        /// <summary>Minimum trust score, 0-10 (null to clear)</summary>
        public int? MinTrustScore { get; set; }
        /// <summary>Update repo-specific quality filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityRepoFilters? RepoFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityRepoFilters RepoFilters { get; set; }
#endif
        /// <summary>Restrict to verified libraries only</summary>
        public bool? RequireVerified { get; set; }
        /// <summary>Update website-specific quality filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityWebsiteFilters? WebsiteFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityWebsiteFilters WebsiteFilters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQuality"/> and sets the default values.
        /// </summary>
        public PatchPoliciesRequestLibraryFiltersQuality()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQuality"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQuality CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQuality();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockedLibraries", n => { BlockedLibraries = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ListOperation>(global::Soenneker.Context7.OpenApiClient.Models.ListOperation.CreateFromDiscriminatorValue); } },
                { "exceptedLibraries", n => { ExceptedLibraries = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ListOperation>(global::Soenneker.Context7.OpenApiClient.Models.ListOperation.CreateFromDiscriminatorValue); } },
                { "maxAgeDays", n => { MaxAgeDays = n.GetIntValue(); } },
                { "minTrustScore", n => { MinTrustScore = n.GetIntValue(); } },
                { "repoFilters", n => { RepoFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityRepoFilters>(global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityRepoFilters.CreateFromDiscriminatorValue); } },
                { "requireVerified", n => { RequireVerified = n.GetBoolValue(); } },
                { "websiteFilters", n => { WebsiteFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityWebsiteFilters>(global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityWebsiteFilters.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ListOperation>("blockedLibraries", BlockedLibraries);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.ListOperation>("exceptedLibraries", ExceptedLibraries);
            writer.WriteIntValue("maxAgeDays", MaxAgeDays);
            writer.WriteIntValue("minTrustScore", MinTrustScore);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityRepoFilters>("repoFilters", RepoFilters);
            writer.WriteBoolValue("requireVerified", RequireVerified);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFiltersQualityWebsiteFilters>("websiteFilters", WebsiteFilters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
