// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Enable or disable specific source types. Both can be provided in one request, but the same type cannot appear in both arrays.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchPoliciesRequestSourceTypes : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Source types to disable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesDisableItem?>? Disable { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesDisableItem?> Disable { get; set; }
#endif
        /// <summary>Source types to enable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesEnableItem?>? Enable { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesEnableItem?> Enable { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes"/> and sets the default values.
        /// </summary>
        public PatchPoliciesRequestSourceTypes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disable", n => { Disable = n.GetCollectionOfEnumValues<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesDisableItem>()?.AsList(); } },
                { "enable", n => { Enable = n.GetCollectionOfEnumValues<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesEnableItem>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesDisableItem>("disable", Disable);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypesEnableItem>("enable", Enable);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
