// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>Filter mode (null to clear)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatchPoliciesRequestLibraryFiltersMode
    {
        [EnumMember(Value = "quality")]
        #pragma warning disable CS1591
        Quality,
        #pragma warning restore CS1591
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
    }
}
