// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Incremental policy update. All fields are optional — only provided fields are modified. At least one of &apos;sourceTypes&apos; or &apos;libraryFilters&apos; must be provided.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PatchPoliciesRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Update library access filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFilters? LibraryFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFilters LibraryFilters { get; set; }
#endif
        /// <summary>Enable or disable specific source types. Both can be provided in one request, but the same type cannot appear in both arrays.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes? SourceTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes SourceTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequest"/> and sets the default values.
        /// </summary>
        public PatchPoliciesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "libraryFilters", n => { LibraryFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFilters>(global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFilters.CreateFromDiscriminatorValue); } },
                { "sourceTypes", n => { SourceTypes = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes>(global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestLibraryFilters>("libraryFilters", LibraryFilters);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PatchPoliciesRequestSourceTypes>("sourceTypes", SourceTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
