// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PatchPoliciesRequestSourceTypesDisableItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "public_repos")]
        #pragma warning disable CS1591
        PublicRepos,
        #pragma warning restore CS1591
        [EnumMember(Value = "private_sources")]
        #pragma warning disable CS1591
        PrivateSources,
        #pragma warning restore CS1591
        [EnumMember(Value = "confluence")]
        #pragma warning disable CS1591
        Confluence,
        #pragma warning restore CS1591
        [EnumMember(Value = "uploaded_files")]
        #pragma warning disable CS1591
        UploadedFiles,
        #pragma warning restore CS1591
        [EnumMember(Value = "websites")]
        #pragma warning disable CS1591
        Websites,
        #pragma warning restore CS1591
        [EnumMember(Value = "llmstxt")]
        #pragma warning disable CS1591
        Llmstxt,
        #pragma warning restore CS1591
    }
}
