// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Complete teamspace policy configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PolicyResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Number of public libraries currently accessible under these filters</summary>
        public int? AccessibleLibraryCount { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Library access filters. Mode determines which sub-object is active.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters? LibraryFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters LibraryFilters { get; set; }
#endif
        /// <summary>Access settings for each documentation source type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes? SourceTypes { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes SourceTypes { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponse"/> and sets the default values.
        /// </summary>
        public PolicyResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PolicyResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PolicyResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessibleLibraryCount", n => { AccessibleLibraryCount = n.GetIntValue(); } },
                { "libraryFilters", n => { LibraryFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters.CreateFromDiscriminatorValue); } },
                { "sourceTypes", n => { SourceTypes = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accessibleLibraryCount", AccessibleLibraryCount);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters>("libraryFilters", LibraryFilters);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes>("sourceTypes", SourceTypes);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
