// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Quality-mode settings (active when mode is &apos;quality&apos;)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PolicyResponseLibraryFiltersQuality : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Libraries excluded from results</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? BlockedLibraries { get; set; }
#nullable restore
#else
        public List<string> BlockedLibraries { get; set; }
#endif
        /// <summary>Libraries that bypass all quality filters, blocked list, and source type restrictions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExceptedLibraries { get; set; }
#nullable restore
#else
        public List<string> ExceptedLibraries { get; set; }
#endif
        /// <summary>Maximum days since last update</summary>
        public int? MaxAgeDays { get; set; }
        /// <summary>Minimum trust score, 0-10</summary>
        public int? MinTrustScore { get; set; }
        /// <summary>Repo-specific quality filters</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityRepoFilters? RepoFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityRepoFilters RepoFilters { get; set; }
#endif
        /// <summary>Restrict to verified libraries only</summary>
        public bool? RequireVerified { get; set; }
        /// <summary>Website-specific quality filters</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityWebsiteFilters? WebsiteFilters { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityWebsiteFilters WebsiteFilters { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality"/> and sets the default values.
        /// </summary>
        public PolicyResponseLibraryFiltersQuality()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockedLibraries", n => { BlockedLibraries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "exceptedLibraries", n => { ExceptedLibraries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "maxAgeDays", n => { MaxAgeDays = n.GetIntValue(); } },
                { "minTrustScore", n => { MinTrustScore = n.GetIntValue(); } },
                { "repoFilters", n => { RepoFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityRepoFilters>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityRepoFilters.CreateFromDiscriminatorValue); } },
                { "requireVerified", n => { RequireVerified = n.GetBoolValue(); } },
                { "websiteFilters", n => { WebsiteFilters = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityWebsiteFilters>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityWebsiteFilters.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("blockedLibraries", BlockedLibraries);
            writer.WriteCollectionOfPrimitiveValues<string>("exceptedLibraries", ExceptedLibraries);
            writer.WriteIntValue("maxAgeDays", MaxAgeDays);
            writer.WriteIntValue("minTrustScore", MinTrustScore);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityRepoFilters>("repoFilters", RepoFilters);
            writer.WriteBoolValue("requireVerified", RequireVerified);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQualityWebsiteFilters>("websiteFilters", WebsiteFilters);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
