// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Access settings for each documentation source type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PolicyResponseSourceTypes : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? Confluence { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus Confluence { get; set; }
#endif
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? Llmstxt { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus Llmstxt { get; set; }
#endif
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? PrivateSources { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus PrivateSources { get; set; }
#endif
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? PublicRepos { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus PublicRepos { get; set; }
#endif
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? UploadedFiles { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus UploadedFiles { get; set; }
#endif
        /// <summary>Whether a source type is enabled or disabled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus? Websites { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus Websites { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes"/> and sets the default values.
        /// </summary>
        public PolicyResponseSourceTypes()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseSourceTypes();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "confluence", n => { Confluence = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
                { "llmstxt", n => { Llmstxt = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
                { "private_sources", n => { PrivateSources = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
                { "public_repos", n => { PublicRepos = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
                { "uploaded_files", n => { UploadedFiles = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
                { "websites", n => { Websites = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>(global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("confluence", Confluence);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("llmstxt", Llmstxt);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("private_sources", PrivateSources);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("public_repos", PublicRepos);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("uploaded_files", UploadedFiles);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.SourceTypeStatus>("websites", Websites);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
