// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>&quot;Filter mode: &apos;quality&apos; for threshold-based filtering, &apos;select&apos; for manual library selection&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PolicyResponseLibraryFiltersMode
    {
        [EnumMember(Value = "quality")]
        #pragma warning disable CS1591
        Quality,
        #pragma warning restore CS1591
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
    }
}
