// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// Library access filters. Mode determines which sub-object is active.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PolicyResponseLibraryFilters : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Filter mode: &apos;quality&apos; for threshold-based filtering, &apos;select&apos; for manual library selection&quot;</summary>
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersMode? Mode { get; set; }
        /// <summary>Quality-mode settings (active when mode is &apos;quality&apos;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality? Quality { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality Quality { get; set; }
#endif
        /// <summary>Select-mode settings (active when mode is &apos;select&apos;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersSelect? Select { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersSelect Select { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters"/> and sets the default values.
        /// </summary>
        public PolicyResponseLibraryFilters()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFilters();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersMode>(); } },
                { "quality", n => { Quality = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality.CreateFromDiscriminatorValue); } },
                { "select", n => { Select = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersSelect>(global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersSelect.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersMode>("mode", Mode);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersQuality>("quality", Quality);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.PolicyResponseLibraryFiltersSelect>("select", Select);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
