// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UsageResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The member who owns the API key, this month. Each member has their own included requests. On the Free plan, the member&apos;s requests stop with a 429 when `requests` reaches `includedInPlan`. On paid plans and `payg`, they continue and count as `teamspace.extraRequests`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.UsageResponseMember? Member { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.UsageResponseMember Member { get; set; }
#endif
        /// <summary>Plan of the teamspace the API key belongs to. `payg` (pay-as-you-go) includes no requests and bills every request.</summary>
        public global::Soenneker.Context7.OpenApiClient.Models.UsageResponsePlan? Plan { get; set; }
        /// <summary>All members of the teamspace together. To get the teamspace&apos;s requests for a period, add up `daily`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace? Teamspace { get; set; }
#nullable restore
#else
        public global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace Teamspace { get; set; }
#endif
        /// <summary>When the monthly numbers in `member` and `teamspace` start again from zero: the first day of next month, UTC. `teamspace.daily` keeps its history.</summary>
        public DateTimeOffset? UsageResetsAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.UsageResponse"/> and sets the default values.
        /// </summary>
        public UsageResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.UsageResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.UsageResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.UsageResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "member", n => { Member = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseMember>(global::Soenneker.Context7.OpenApiClient.Models.UsageResponseMember.CreateFromDiscriminatorValue); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponsePlan>(); } },
                { "teamspace", n => { Teamspace = n.GetObjectValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace>(global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace.CreateFromDiscriminatorValue); } },
                { "usageResetsAt", n => { UsageResetsAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseMember>("member", Member);
            writer.WriteEnumValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponsePlan>("plan", Plan);
            writer.WriteObjectValue<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace>("teamspace", Teamspace);
            writer.WriteDateTimeOffsetValue("usageResetsAt", UsageResetsAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
