// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>
    /// All members of the teamspace together. To get the teamspace&apos;s requests for a period, add up `daily`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsageResponseTeamspace : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Requests of all members per UTC day, oldest first. Every day is present; days without requests are 0.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspaceDailyItem>? Daily { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspaceDailyItem> Daily { get; set; }
#endif
        /// <summary>Cost of `extraRequests` in US dollars, as it will appear on the invoice. Always 0 on the Free plan.</summary>
        public double? ExtraCostUsd { get; set; }
        /// <summary>Requests this month beyond each member&apos;s `includedInPlan`. Always 0 on the Free plan.</summary>
        public int? ExtraRequests { get; set; }
        /// <summary>Monthly limit for `extraCostUsd` in US dollars. When `extraCostUsd` reaches it, search and docs requests return 402 until `resetsAt`. `null` if no limit is set.</summary>
        public double? SpendingLimitUsd { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace"/> and sets the default values.
        /// </summary>
        public UsageResponseTeamspace()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspace();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "daily", n => { Daily = n.GetCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspaceDailyItem>(global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspaceDailyItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "extraCostUsd", n => { ExtraCostUsd = n.GetDoubleValue(); } },
                { "extraRequests", n => { ExtraRequests = n.GetIntValue(); } },
                { "spendingLimitUsd", n => { SpendingLimitUsd = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Context7.OpenApiClient.Models.UsageResponseTeamspaceDailyItem>("daily", Daily);
            writer.WriteDoubleValue("extraCostUsd", ExtraCostUsd);
            writer.WriteIntValue("extraRequests", ExtraRequests);
            writer.WriteDoubleValue("spendingLimitUsd", SpendingLimitUsd);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
