// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Context7.OpenApiClient.Models
{
    /// <summary>Plan of the teamspace the API key belongs to. `payg` (pay-as-you-go) includes no requests and bills every request.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UsageResponsePlan
    {
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "pro")]
        #pragma warning disable CS1591
        Pro,
        #pragma warning restore CS1591
        [EnumMember(Value = "enterprise")]
        #pragma warning disable CS1591
        Enterprise,
        #pragma warning restore CS1591
        [EnumMember(Value = "payg")]
        #pragma warning disable CS1591
        Payg,
        #pragma warning restore CS1591
    }
}
