// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Context7.OpenApiClient.V2.Add.Repo.Bitbucket;
using Soenneker.Context7.OpenApiClient.V2.Add.Repo.Git;
using Soenneker.Context7.OpenApiClient.V2.Add.Repo.Github;
using Soenneker.Context7.OpenApiClient.V2.Add.Repo.Gitlab;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Context7.OpenApiClient.V2.Add.Repo
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\add\repo
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RepoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The bitbucket property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Bitbucket.BitbucketRequestBuilder Bitbucket
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Bitbucket.BitbucketRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The git property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Git.GitRequestBuilder Git
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Git.GitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The github property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Github.GithubRequestBuilder Github
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Github.GithubRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The gitlab property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Gitlab.GitlabRequestBuilder Gitlab
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.Gitlab.GitlabRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.RepoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RepoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/add/repo", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.RepoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RepoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/add/repo", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
