// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Context7.OpenApiClient.V2.Add.Confluence;
using Soenneker.Context7.OpenApiClient.V2.Add.Llmstxt;
using Soenneker.Context7.OpenApiClient.V2.Add.Notion;
using Soenneker.Context7.OpenApiClient.V2.Add.Openapi;
using Soenneker.Context7.OpenApiClient.V2.Add.OpenapiUpload;
using Soenneker.Context7.OpenApiClient.V2.Add.Repo;
using Soenneker.Context7.OpenApiClient.V2.Add.Website;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Context7.OpenApiClient.V2.Add
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\add
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The confluence property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Confluence.ConfluenceRequestBuilder Confluence
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Confluence.ConfluenceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The llmstxt property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Llmstxt.LlmstxtRequestBuilder Llmstxt
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Llmstxt.LlmstxtRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notion property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Notion.NotionRequestBuilder Notion
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Notion.NotionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The openapi property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Openapi.OpenapiRequestBuilder Openapi
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Openapi.OpenapiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The openapiUpload property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.OpenapiUpload.OpenapiUploadRequestBuilder OpenapiUpload
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.OpenapiUpload.OpenapiUploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repo property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.RepoRequestBuilder Repo
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Repo.RepoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The website property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Add.Website.WebsiteRequestBuilder Website
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Add.Website.WebsiteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Add.AddRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/add", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Add.AddRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AddRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/add", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
