// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Context7.OpenApiClient.V2.Libs.Metrics;
using Soenneker.Context7.OpenApiClient.V2.Libs.Search;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Context7.OpenApiClient.V2.Libs
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\libs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LibsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The metrics property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Libs.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Libs.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Context7.OpenApiClient.V2.Libs.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Context7.OpenApiClient.V2.Libs.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Libs.LibsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/libs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Context7.OpenApiClient.V2.Libs.LibsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LibsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/libs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
